/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ragialdesktopalarm.Forms;

import ragialdesktopalarm.Parsing.ParseItemInfo;
import ragialdesktopalarm.ROItem;
import ragialdesktopalarm.ROItems;

/**
 *
 * @author jko
 */
public class PreviewForm extends javax.swing.JFrame {
    
    private static PreviewForm obj = null;
    
    ROItem thisItem;
    
    private PreviewForm(String selected) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        showItemInfo(selected);
        ParseItemInfo parse = new ParseItemInfo(thisItem.getLink());
        lowestPrice.setText(parse.lowestPrice);
    }
    
    public static PreviewForm getObj(String s){
        if(obj == null){
            obj = new PreviewForm(s);
        } else {
            obj.dispose();
            obj = new PreviewForm(s);
        }
        return obj;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemName = new javax.swing.JLabel();
        test = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        vendPrice = new javax.swing.JLabel();
        lowestPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(408, 192));
        setResizable(false);
        setSize(new java.awt.Dimension(408, 192));
        getContentPane().setLayout(null);

        itemName.setFont(new java.awt.Font("Univers LT 45 Light", 0, 14)); // NOI18N
        itemName.setText("jLabel1");
        getContentPane().add(itemName);
        itemName.setBounds(38, 26, 380, 18);

        test.setFont(new java.awt.Font("Univers LT 45 Light", 0, 14)); // NOI18N
        test.setText("You are vending it for:");
        getContentPane().add(test);
        test.setBounds(38, 62, 141, 18);

        jLabel1.setFont(new java.awt.Font("Univers LT 45 Light", 0, 14)); // NOI18N
        jLabel1.setText("Lowest Price for this item:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(38, 98, 169, 18);

        vendPrice.setFont(new java.awt.Font("Univers LT 45 Light", 0, 14)); // NOI18N
        vendPrice.setText("jLabel2");
        getContentPane().add(vendPrice);
        vendPrice.setBounds(305, 60, 110, 18);

        lowestPrice.setFont(new java.awt.Font("Univers LT 45 Light", 0, 14)); // NOI18N
        lowestPrice.setText("jLabel2");
        getContentPane().add(lowestPrice);
        lowestPrice.setBounds(305, 100, 110, 18);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel itemName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lowestPrice;
    private javax.swing.JLabel test;
    private javax.swing.JLabel vendPrice;
    // End of variables declaration//GEN-END:variables

    private void showItemInfo(String s) {
        ROItems items = AlarmForm.currentItems;
        for (int i = 0 ; i < items.getSize(); i ++){
            if (items.get(i).getName().equals(s)){
                thisItem = items.get(i);
            }
        }
        itemName.setText(thisItem.getName());
        vendPrice.setText(thisItem.getPrice());
    }
  
}
